#!/bin/bash
clear
echo "The number of succesful requests per hour:" > result.txt
echo -n "13:00:00 - 13:59:59 " >> result.txt
grep '15/Oct/2014:13:' datamining.log | grep -wc '200' >> result.txt
echo -n "14:00:00 - 14:59:59 " >> result.txt
grep '15/Oct/2014:14:' datamining.log | grep -wc '200' >> result.txt
echo -n "15:00:00 - 15:59:59 " >> result.txt
grep '15/Oct/2014:15:' datamining.log | grep -wc '200' >> result.txt
echo -n "16:00:00 - 16:59:59 " >> result.txt
grep '15/Oct/2014:16:' datamining.log | grep -wc '200' >> result.txt



echo "...done! result.txt saved"
